fit:
  compile: true
  float32_matmul_precision: medium
  trainer:
    accelerator: gpu
    devices: 2
    strategy: "ddp"
    precision: "bf16-mixed"
    max_steps: 100000
    num_sanity_val_steps: 2
    default_root_dir: /mnt/flash/vindr
    #accumulate_grad_batches: 4
    check_val_every_n_epoch: 10
    callbacks:
      - class_path: pytorch_lightning.callbacks.ModelCheckpoint
        init_args:
          filename: "epoch={epoch}-step={step}-loss={val/loss:.4f}"
          monitor: "val/loss"
          auto_insert_metric_name: false
          mode: min
          save_last: true

      - class_path: pytorch_lightning.callbacks.LearningRateMonitor
        init_args:
          log_momentum: true

    logger:
      class_path: pytorch_lightning.loggers.wandb.WandbLogger
      init_args:
        save_dir: /mnt/flash/vindr
        project: vindr
        name: vindr-base-p1

  model:
    class_path: mit_ub.tasks.JEPA
    init_args:
      backbone: "vit-i1-p16-d512"
      log_train_metrics_interval: 50

      # JEPA parameters
      ema_alpha: 0.98
      weight_decay_final: null
      momentum_schedule: false
      predictor_depth: 4
      context_ratio: 0.5
      target_ratio: 0.25
      context_subsample_ratio: 0.5
      context_scale: 2
      target_scale: 2

      optimizer_init:
        class_path: bitsandbytes.optim.AdamW8bit
        init_args:
          lr: 0.00025
          weight_decay: 0.05
          betas: [0.85, 0.999]
      lr_interval: "step"
      lr_scheduler_init:
        class_path: deep_helpers.optim.ReciprocalSquareRootLR
        init_args:
          warmup_steps: 5000
          cooldown_steps: 25000
          total_steps: 100000
          timescale: 10000
          initial_lr: 0.00005
          initial_momentum: 0.95
      parameter_groups:
        - params:
            - "jepa_predictor"
            - "jepa_out_proj"
          weight_decay: 0.25

  data:
    class_path: mit_ub.data.VinDrDataModule
    init_args:
      root: "/mnt/data/vindr/lowres"

      batch_size: 32
      num_workers: 12
      pin_memory: true

      train_transforms:
        class_path: torchvision.transforms.v2.Compose
        init_args:
          transforms:

            - class_path: torchvision.transforms.v2.RandomResizedCrop
              init_args:
                size: [512, 384]
                scale: [0.8, 1.0]
                ratio: [0.8, 1.2]
                antialias: true

      train_gpu_transforms:
        class_path: torchvision.transforms.v2.Compose
        init_args:
          transforms:
            - class_path: torchvision.transforms.v2.RandomHorizontalFlip
              init_args:
                p: 0.5

            - class_path: torchvision.transforms.v2.RandomVerticalFlip
              init_args:
                p: 0.5

            - class_path: torchvision.transforms.v2.ColorJitter
              init_args:
                brightness: 0.2
                contrast: 0.2

            - class_path: torchvision.transforms.v2.RandomInvert
              init_args:
                p: 0.5

      val_transforms:
        class_path: torchvision.transforms.v2.Resize
        init_args:
          size: [512, 384]
          antialias: true