fit:
  compile: true
  float32_matmul_precision: medium
  trainer:
    accelerator: gpu
    devices: 2
    strategy: "ddp"
    precision: "bf16-mixed"
    max_steps: 500000
    num_sanity_val_steps: 0
    default_root_dir: /mnt/storage/users/chase/mitub
    val_check_interval: 5000
    #check_val_every_n_epoch: 10
    callbacks:
      - class_path: pytorch_lightning.callbacks.ModelCheckpoint
        init_args:
          filename: "epoch={epoch}-step={step}-loss={val/loss:.4f}"
          monitor: "val/loss"
          auto_insert_metric_name: false
          mode: min
          save_last: true

      - class_path: pytorch_lightning.callbacks.LearningRateMonitor
        init_args:
          log_momentum: true

    logger:
      class_path: pytorch_lightning.loggers.wandb.WandbLogger
      init_args:
        save_dir: /mnt/storage/users/chase/mitub
        project: mit-ub
        name: mitub-rev4-large-mjepa-triage

  model:
    class_path: mit_ub.tasks.BreastTriage
    init_args:
      backbone: "vit-i1-p16-d768-a32_24"
      #checkpoint: /mnt/storage/users/chase/mitub/mit-ub/lmj01ch6/checkpoints/last.ckpt
      #checkpoint: /mnt/storage/users/chase/mitub/mit-ub/tzm3hgq0/checkpoints/last.ckpt
      checkpoint: /mnt/storage/users/chase/mitub/mit-ub/f9lk7i0a/checkpoints/last.ckpt
      strict_checkpoint: false

      log_train_metrics_interval: 50
      optimizer_init:
        class_path: torch.optim.AdamW
        init_args:
          lr: 0.00002
          weight_decay: 0.05
      weight_decay_exemptions:
        - "bias"
        - "LayerNorm"
      lr_interval: "step"
      lr_scheduler_init:
        class_path: torch.optim.lr_scheduler.OneCycleLR
        init_args:
          max_lr: 0.00002
          div_factor: 2
          final_div_factor: 50
          pct_start: 0.10
          three_phase: false
          total_steps: 500000

  data:
    class_path: mit_ub.data.triage.PreprocessedPNGDataModule
    init_args:

      train_inputs: 
        - "/mnt/active_1/chase/data/optimam_highres"
        - "/mnt/active_1/chase/data/medcog_highres"
        #- "/mnt/active_2/chase/data/test"
      val_inputs: 
        #- "/mnt/active_2/chase/data/test"
        - "/mnt/active_2/chase/data/test"

      batch_size: 4
      num_workers: 12
      pin_memory: true
      persistent_workers: true
      malign_weight: 0.33

      metadata_filenames:
        manifest: "manifest.csv"
        annotation: "annotation.csv"
      boxes_filename: "traces.csv"
      boxes_extra_keys:
        - "trait"
        - "types"

      train_transforms:
        class_path: torchvision.transforms.v2.Compose
        init_args:
          transforms:

            - class_path: torchvision.transforms.v2.RandomResizedCrop
              init_args:
                size: [3072, 2304]
                scale: [0.8, 1.0]
                ratio: [0.8, 1.2]
                antialias: true

      train_gpu_transforms:
        class_path: torchvision.transforms.v2.Compose
        init_args:
          transforms:
            - class_path: torchvision.transforms.v2.RandomHorizontalFlip
              init_args:
                p: 0.5

            - class_path: torchvision.transforms.v2.RandomVerticalFlip
              init_args:
                p: 0.5

            - class_path: torchvision.transforms.v2.ColorJitter
              init_args:
                brightness: 0.2
                contrast: 0.2

            - class_path: torchvision.transforms.v2.RandomInvert
              init_args:
                p: 0.5

      val_transforms:
        class_path: torchvision.transforms.v2.Resize
        init_args:
          size: [3072, 2304]
          antialias: true