fit:
  compile: true
  float32_matmul_precision: medium
  trainer:
    accelerator: gpu
    devices: 2
    strategy: "ddp_find_unused_parameters_true"
    precision: "bf16-mixed"
    #precision: "16-mixed"
    max_steps: 250000
    num_sanity_val_steps: 0
    default_root_dir: /mnt/storage/users/chase/mitub
    gradient_clip_val: 5.0
    gradient_clip_algorithm: "norm"
    #check_val_every_n_epoch: 5
    callbacks:
      - class_path: pytorch_lightning.callbacks.ModelCheckpoint
        init_args:
          filename: "epoch={epoch}-step={step}-loss={val/loss:.4f}"
          monitor: "val/loss"
          auto_insert_metric_name: false
          mode: min
          save_last: true

      - class_path: pytorch_lightning.callbacks.LearningRateMonitor
        init_args:
          log_momentum: true

      #- class_path: mit_ub.callbacks.LogInputCallback
      #  init_args:
      #    name: input
      #    modes:
      #      - "TRAIN"
      #    queue_size: 4
      #    flush_interval: 1000

      #- class_path: mit_ub.callbacks.LogInputCallback
      #  init_args:
      #    name: input
      #    modes:
      #      - "VAL"
      #      - "TEST"
      #    queue_size: 4

      - class_path: mit_ub.callbacks.HistogramCallback
        init_args:
          name: histogram

      #- class_path: mit_ub.callbacks.LogMAECallback
      #  init_args:
      #    name: input
      #    modes:
      #      - "TRAIN"
      #    queue_size: 4
      #    flush_interval: 1000

      #- class_path: deep_helpers.callbacks.MultiTaskCallbackWrapper
      #  init_args:
      #    wrapped:
      #      class_path: mit_ub.callbacks.LogMAECallback
      #      init_args:
      #        name: input
      #        modes:
      #          - "TRAIN"
      #        queue_size: 4
      #        flush_interval: 50
      #    tasks:
      #      - "mae"

    logger:
      class_path: pytorch_lightning.loggers.wandb.WandbLogger
      init_args:
        save_dir: /mnt/storage/users/chase/mitub
        project: mit-ub

  model:
    class_path: mit_ub.tasks.JEPA
    init_args:
      backbone: "vit-i1-p16-d512"
      #loss_includes_unmasked: false
      #mask_scale: 2
      #mask_ratio: 0.5
      optimizer_init:
        class_path: torch.optim.AdamW
        init_args:
          lr: 0.00002
          weight_decay: 0.05
      weight_decay_exemptions:
        - "bias"
        - "LayerNorm"
        - "position"
      lr_interval: "step"
      lr_scheduler_init:
        class_path: torch.optim.lr_scheduler.OneCycleLR
        init_args:
          max_lr: 0.00002
          div_factor: 2
          final_div_factor: 50
          pct_start: 0.10
          three_phase: false
          total_steps: 250000
      #checkpoint: /mnt/storage/users/chase/models/jepa.ckpt
      #strict_checkpoint: false

  data:
    class_path: torch_dicom.preprocessing.datamodule.PreprocessedPNGDataModule
    init_args:
      train_inputs: 
        - "/mnt/active_2/chase/data/medcog"
        - "/mnt/active_2/chase/data/optimam"
        - "/mnt/active_2/chase/data/optimam_proc"
      val_inputs: /mnt/active_1/chase/data/val
      #train_sopuid_exclusions: /mnt/active_1/chase/data/train_density_exclude.csv
      #val_sopuid_exclusions: /mnt/active_1/chase/data/test_density_exclude.csv
      #metadata_filenames:
      #  manifest: "manifest.csv"
      #  #annotation: "autoannotation.csv"
      metadata_filenames:
        manifest: "manifest.csv"
        annotation: "autoannotation.csv"
      boxes_filename: "traces.csv"
      boxes_extra_keys:
        - "trait"
        - "types"

      batch_size: 64
      num_workers: 0
      pin_memory: true

      train_transforms:
        class_path: torchvision.transforms.v2.Compose
        init_args:
          transforms:
            - class_path: torchvision.transforms.v2.RandomRotation
              init_args:
                degrees: 20

            - class_path: torchvision.transforms.v2.RandomResizedCrop
              init_args:
                size: [512, 384]
                scale: [0.8, 1.0]
                ratio: [0.8, 1.2]
                antialias: true

      train_gpu_transforms:
        class_path: torchvision.transforms.v2.Compose
        init_args:
          transforms:
            - class_path: torchvision.transforms.v2.RandomHorizontalFlip
              init_args:
                p: 0.5

            - class_path: torchvision.transforms.v2.RandomVerticalFlip
              init_args:
                p: 0.5

            - class_path: torchvision.transforms.v2.ColorJitter
              init_args:
                brightness: 0.2
                contrast: 0.2

            - class_path: torchvision.transforms.v2.RandomInvert
              init_args:
                p: 0.5

      #val_transforms:
      #  class_path: torchvision.transforms.v2.Compose
      #  init_args:
      #    transforms:
      #      - class_path: torchvision.transforms.v2.Resize
      #        init_args:
      #          size: 256
      #          antialias: true